name: Build iOS

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
  
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          architecture: x64
      
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
