name: Lint & Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
      
      - name: Get dependencies
        run: flutter pub get
      - name: Linting
        run: flutter analyze
      - name: Build APK
        run: flutter build apk --release --split-per-abi
      - name: Build Bundle
        run: flutter build appbundle
      
      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v2
        with:
          name: app.apk
          path: build/app/outputs/flutter-apk/app.apk
          if-no-files-found: error
      
      - name: Upload Artifact (SHA)
        uses: actions/upload-artifact@v2
        with:
          name: app.apk.sha1
          path: build/app/outputs/flutter-apk/app.apk.sha1
          if-no-files-found: error
      
      - name: Upload Artifact (Bundle)
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
